version: '3'
services:
        web:
                image: runtime_t_v1
                build: .
                ports:
                        - "8032:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped