version: ‘1’
services:
        web:
                image: runtime_terror_v1
                build: .
                ports:
                        - “8123:8123”
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped